// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wulpofamlxtivruqleqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1bHBvZmFtbHh0aXZydXFsZXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjY4OTAsImV4cCI6MjA2MDIwMjg5MH0.C-y5RALhy2VNAKVlUky0UE5vXfw2jQZrBtgdUg1DLz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);